version: "3.7"
services:
    app: 
      image: galfrylich/web-app
      depends_on:
        - db
      links:
        - db 
      ports: 
        - "5000:5000"
      environment:
        REMOTE_IP: ${REMOTE_IP}
        REMOT_UNAME: ${REMOT_UNAME}
        REMOT_PASS: ${REMOT_PASS}
        DB_HOST: ${DB_HOST}
        DB_UNAME: ${DB_UNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      hostname: db  
      environment:
        DB_PASSWORD: ${DB_PASSWORD}
      healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "db"]
            timeout: 20s
            retries: 10  
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro