version: "3.7"
services:
    app: 
      build: .
      links:
        - db 
      ports: 
        - "5000:5000"
      environment:
        REMOTE_IP: ${REMOTE_IP}
        REMOT_UNAME: ${REMOT_UNAME}
        REMOT_PASS: ${REMOT_PASS}
        DB_HOST: ${DB_HOST}
        DB_UNAME: ${DB_UNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      hostname: db   
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      #volumes:
       # - db-data:/var/lib/mysql/data 